let isActive = true
let totalOccurrences = 0
const ELEMENT_DONE_CLASSNAME = '__micalevisk_ext_coronguese__'

const isGooglePage = document.location.hostname.startsWith('www.google.')
const isDuckDuckGoPage = document.location.hostname.startsWith('duckduckgo.')
const isBingPage = document.location.hostname.startsWith('www.bing.')

const blacklistRegExp = (function(){
  const blacklistWordsRE = [
    'coronav[ií]rus',
    'corona\sv[ií]rus',
    'covid-?19',
    'covid',
  ]
  return new RegExp(`\\b${blacklistWordsRE.join('|')}\\b`, 'gi')
}())

const getEmoji = (function(){
  const emojis = [
    //'🦠',
    '💉',
  ]
  let i=0
  return () => emojis[i++ % emojis.length]
}())

const isValidURL = (strMaybeURL) => {
  try {
    new URL(strMaybeURL)
    return true
  } catch (_err) {
    return false
  }
}

const hasURLContent = (textNode) => {
  if (textNode.parentNode.nodeName !== 'A') {
    return isValidURL(textNode.nodeValue)
  }
  return isValidURL(textNode.nodeValue) || textNode.parentNode.href.includes(textNode.textContent)
  //                                       ^^ If the text content is be a shorten URL generated by Refined GitHub extension
}

const replaceTextsOnNode = (textNode) => {
  const parent = textNode.parentNode
  const normalizedNodeValue = textNode.nodeValue.trim()
  let occurrences = 0

  // Custom filters to prevent replace in non-valid texts node
  const isGoogleBreadcrumb = isGooglePage && normalizedNodeValue.includes(' › ')
  const isGoogleHrefContent = isGooglePage && parent.className.includes('HRf')
  const isDDGURL = isDuckDuckGoPage && parent.className.includes('result__url')
  const isBingBreadcrumb = isBingPage && ( parent.tagName === 'CITE' && parent.parentNode.classList.contains('b_attribution') )
  const isURL = hasURLContent(textNode)

  const canSearchAndReplace = !isURL && !isGoogleBreadcrumb && !isGoogleHrefContent && !isDDGURL && !isBingBreadcrumb
  if (canSearchAndReplace) {
    const replacer = (match) => {
      occurrences++
      const newValue = getEmoji()
      return `<span class="${ELEMENT_DONE_CLASSNAME}" data-modified="${newValue}" data-original="${match}"></span>`
    }

    const newValue = normalizedNodeValue.replace(blacklistRegExp, replacer)
    if (occurrences > 0) {
      const wrapperEl = document.createElement('template')
      wrapperEl.innerHTML = newValue
      textNode.replaceWith(wrapperEl.content)
    }
  }

  return occurrences
}

const replaceAllAndUpdateBadge = (function(){
  const tagsNameToIgnore = ['SCRIPT', 'NOSCRIPT', 'STYLE', 'SOURCE', 'TITLE', 'META']
  return () => {
    const nodeIt = document.createNodeIterator(
      document.body,
      NodeFilter.SHOW_TEXT,
      (node) =>
          (
            !tagsNameToIgnore.includes(node.parentNode.nodeName) &&
            node.nodeValue.trim() &&
            !node.parentNode.classList.contains(ELEMENT_DONE_CLASSNAME)
          )
        ? NodeFilter.FILTER_ACCEPT
        : NodeFilter.FILTER_REJECT
    )

    while (nodeIt.nextNode()) {
      totalOccurrences += replaceTextsOnNode(nodeIt.referenceNode)
    }

    if (isActive) {
      chrome.runtime.sendMessage({
        action: 'set-tracker-count',
        count: totalOccurrences,
      })
    }
  }
}())

const toggleVisibility = (function(){ 
  const attrSources = ['data-original', 'data-modified']
  return (isActive) =>
    document.documentElement.style.setProperty('--coronguese-source', attrSources[+isActive]) 
}())


chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request === 'toggle-tab') {
    isActive = !isActive
    sendResponse({ isActive, count: totalOccurrences })
    toggleVisibility(isActive)
  }
})

document.body.addEventListener('transitionend', ({ isTrusted }) =>
  isTrusted && replaceAllAndUpdateBadge(), true)


replaceAllAndUpdateBadge()

